import json

notebook = {
 "nbformat": 4,
 "nbformat_minor": 0,
 "metadata": {
  "accelerator": "GPU",
  "colab": {"gpuType": "T4", "provenance": []},
  "kernelspec": {"display_name": "Python 3", "name": "python3"},
  "language_info": {"name": "python"}
 },
 "cells": [
  {"cell_type": "markdown", "metadata": {}, "source": [
   "# NetraEdge - Liveness Detection Training\n",
   "## LivenessCNN: Real vs Print vs Screen\n",
   "## GPU: T4 | Time: ~1 hour\n",
   "## Output: liveness_detector.onnx"
  ]},
  {"cell_type": "code", "metadata": {}, "source": [
   "#@title Step 1: Setup\n",
   "import torch\n",
   "print('PyTorch:', torch.__version__)\n",
   "if torch.cuda.is_available():\n",
   "    print('GPU:', torch.cuda.get_device_name())\n",
   "else:\n",
   "    print('No GPU! Runtime > Change runtime type > GPU')\n",
   "!pip install -q onnx tqdm"
  ], "outputs": [], "execution_count": None},
  {"cell_type": "code", "metadata": {}, "source": [
   "#@title Step 2: Download LFW\n",
   "import tarfile, os, random\n",
   "from urllib.request import urlretrieve\n",
   "if not os.path.exists('lfw'):\n",
   "    print('Downloading LFW...')\n",
   "    urlretrieve('http://vis-www.cs.umass.edu/lfw/lfw-funneled.tgz', 'lfw.tgz')\n",
   "    with tarfile.open('lfw.tgz', 'r:gz') as t:\n",
   "        t.extractall('.')\n",
   "ids = [d for d in os.listdir('lfw') if os.path.isdir('lfw/' + d)]\n",
   "print('LFW:', len(ids), 'identities')"
  ], "outputs": [], "execution_count": None},
  {"cell_type": "code", "metadata": {}, "source": [
   "#@title Step 3: LivenessCNN Architecture\n",
   "import torch.nn as nn\n",
   "import torch.nn.functional as F\n",
   "\n",
   "class LBlock(nn.Module):\n",
   "    def __init__(self, ic, oc, st=1):\n",
   "        super().__init__()\n",
   "        self.dw = nn.Conv2d(ic, ic, 3, st, 1, groups=ic, bias=False)\n",
   "        self.b1 = nn.BatchNorm2d(ic)\n",
   "        self.pw = nn.Conv2d(ic, oc, 1, bias=False)\n",
   "        self.b2 = nn.BatchNorm2d(oc)\n",
   "    def forward(self, x):\n",
   "        return F.relu(self.b2(self.pw(F.relu(self.b1(self.dw(x))))))\n",
   "\n",
   "class LivenessCNN(nn.Module):\n",
   "    def __init__(self, nc=3, dp=0.3):\n",
   "        super().__init__()\n",
   "        self.feat = nn.Sequential(\n",
   "            nn.Conv2d(3, 32, 3, 2, 1, bias=False), nn.BatchNorm2d(32), nn.ReLU(True),\n",
   "            LBlock(32, 64), LBlock(64, 128, 2),\n",
   "            LBlock(128, 256, 2), LBlock(256, 256, 2))\n",
   "        self.cls = nn.Sequential(\n",
   "            nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n",
   "            nn.Dropout(dp), nn.Linear(256, 64), nn.ReLU(True),\n",
   "            nn.Dropout(dp * 0.5), nn.Linear(64, nc))\n",
   "        for m in self.modules():\n",
   "            if isinstance(m, nn.Conv2d):\n",
   "                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')\n",
   "            elif isinstance(m, nn.BatchNorm2d):\n",
   "                nn.init.constant_(m.weight, 1)\n",
   "                nn.init.constant_(m.bias, 0)\n",
   "    def forward(self, x):\n",
   "        return self.cls(self.feat(x))\n",
   "    def predict_proba(self, x):\n",
   "        return F.softmax(self.forward(x), dim=1)\n",
   "\n",
   "m = LivenessCNN(3)\n",
   "out = m(torch.randn(2, 3, 112, 112))\n",
   "np = sum(p.numel() for p in m.parameters())\n",
   "print('LivenessCNN:', np, 'params, output:', out.shape)"
  ], "outputs": [], "execution_count": None},
  {"cell_type": "code", "metadata": {}, "source": [
   "#@title Step 4: Synthetic Liveness Dataset\n",
   "from torch.utils.data import Dataset, DataLoader\n",
   "from PIL import Image\n",
   "import numpy as np\n",
   "\n",
   "class SynLiveness(Dataset):\n",
   "    def __init__(self, root='lfw', ns=3000):\n",
   "        self.imgs = []\n",
   "        for r, ds, fs in os.walk(root):\n",
   "            for f in fs:\n",
   "                if f.endswith('.jpg'):\n",
   "                    self.imgs.append(os.path.join(r, f))\n",
   "        self.ns = ns\n",
   "        print('Found', len(self.imgs), 'source images')\n",
   "    def __len__(self):\n",
   "        return self.ns\n",
   "    def __getitem__(self, idx):\n",
   "        path = random.choice(self.imgs)\n",
   "        label = idx % 3\n",
   "        img = Image.open(path).convert('RGB').resize((112, 112))\n",
   "        arr = np.array(img).astype(np.float32) / 255.0\n",
   "        if label == 1:\n",
   "            arr = np.clip(arr * 1.1 + 0.04, 0, 1)\n",
   "            k = np.ones(9) / 9\n",
   "            arr = np.stack([np.convolve(arr[:,:,c].flatten(), k, mode='same').reshape(112,112) for c in range(3)], -1)\n",
   "        elif label == 2:\n",
   "            for y in range(0, 112, 2):\n",
   "                arr[y,:,:] *= 0.85\n",
   "            arr[:,:,2] *= 1.1\n",
   "            arr = arr * 0.8 + 0.12\n",
   "        arr = np.clip(arr + np.random.normal(0, 0.02, arr.shape), 0, 1)\n",
   "        if random.random() > 0.5:\n",
   "            arr = np.flip(arr, axis=1).copy()\n",
   "        tensor = torch.from_numpy(arr).permute(2, 0, 1).float()\n",
   "        mean = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)\n",
   "        std = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)\n",
   "        return (tensor - mean) / std, label\n",
   "\n",
   "tr = SynLiveness('lfw', 3000)\n",
   "va = SynLiveness('lfw', 600)\n",
   "trl = DataLoader(tr, 64, shuffle=True, num_workers=2, pin_memory=True)\n",
   "val_loader = DataLoader(va, 64, shuffle=False, num_workers=2)\n",
   "print('Train:', len(tr), 'Val:', len(va))"
  ], "outputs": [], "execution_count": None},
  {"cell_type": "code", "metadata": {}, "source": [
   "#@title Step 5: Train (15 epochs)\n",
   "import time\n",
   "from tqdm import tqdm\n",
   "\n",
   "D = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
   "m = LivenessCNN(3).to(D)\n",
   "w = torch.tensor([1.0, 1.5, 1.5]).to(D)\n",
   "criterion = nn.CrossEntropyLoss(weight=w, label_smoothing=0.1)\n",
   "opt = torch.optim.AdamW(m.parameters(), lr=5e-4, weight_decay=1e-4)\n",
   "sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=15, eta_min=1e-6)\n",
   "best = 0\n",
   "\n",
   "for ep in range(15):\n",
   "    t0 = time.time()\n",
   "    m.train()\n",
   "    tc = tt = 0\n",
   "    for x, y in tqdm(trl, desc='Ep ' + str(ep+1) + '/15'):\n",
   "        x, y = x.to(D), y.to(D)\n",
   "        opt.zero_grad()\n",
   "        loss = criterion(m(x), y)\n",
   "        loss.backward()\n",
   "        torch.nn.utils.clip_grad_norm_(m.parameters(), 5.0)\n",
   "        opt.step()\n",
   "        tc += (m(x).argmax(1) == y).sum().item()\n",
   "        tt += y.size(0)\n",
   "    m.eval()\n",
   "    vc = vt = 0\n",
   "    with torch.no_grad():\n",
   "        for x, y in val_loader:\n",
   "            x, y = x.to(D), y.to(D)\n",
   "            vc += (m(x).argmax(1) == y).sum().item()\n",
   "            vt += y.size(0)\n",
   "    ta = 100 * tc / tt\n",
   "    vAcc = 100 * vc / vt\n",
   "    sch.step()\n",
   "    elapsed = int(time.time() - t0)\n",
   "    print('Ep ' + str(ep+1) + ': Train ' + str(round(ta,1)) + '% Val ' + str(round(vAcc,1)) + '% ' + str(elapsed) + 's')\n",
   "    if vAcc > best:\n",
   "        best = vAcc\n",
   "        torch.save(m.state_dict(), 'liv_best.pt')\n",
   "        print('  Saved (' + str(round(vAcc,1)) + '%)')\n",
   "print('Best: ' + str(round(best,1)) + '%')"
  ], "outputs": [], "execution_count": None},
  {"cell_type": "code", "metadata": {}, "source": [
   "#@title Step 6: Export ONNX\n",
   "m.cpu().eval()\n",
   "torch.onnx.export(m, torch.randn(1, 3, 112, 112),\n",
   "    'liveness_detector.onnx',\n",
   "    input_names=['input'], output_names=['output'], opset_version=13)\n",
   "import os\n",
   "sz = os.path.getsize('liveness_detector.onnx') / 1e6\n",
   "print('Exported: liveness_detector.onnx (' + str(round(sz,1)) + 'MB)')\n",
   "print('Download and place in F:/PROJECTS/NetraEdge/models/')"
  ], "outputs": [], "execution_count": None}
 ]
}

with open(r'F:\PROJECTS\NetraEdge\training\notebooks\train_liveness.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)

with open(r'F:\PROJECTS\NetraEdge\training\notebooks\train_liveness.ipynb') as f:
    json.load(f)
print('train_liveness.ipynb valid!')
