import json

# ============ RECOGNITION NOTEBOOK ============
rec_cells = [
    {"cell_type": "markdown", "metadata": {}, "source": [
        "# NetraEdge - Face Recognition Training\n",
        "## MobileFaceNet | GPU: T4 | Time: ~2 hours"
    ]},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 1: Install + GPU Check\n",
        "!pip install -q onnx tqdm scikit-learn onnxscript\n",
        "import torch\n",
        "print('PyTorch:', torch.__version__)\n",
        "if torch.cuda.is_available():\n",
        "    print('GPU:', torch.cuda.get_device_name())\n",
        "else:\n",
        "    print('WARNING: No GPU! Runtime > Change runtime type > GPU')"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 2: Load LFW Dataset\n",
        "from sklearn.datasets import fetch_lfw_people\n",
        "from PIL import Image\n",
        "import numpy as np\n",
        "import os\n",
        "\n",
        "print('Loading LFW via sklearn...')\n",
        "lfw = fetch_lfw_people(min_faces_per_person=20, resize=0.5, color=True)\n",
        "print('Loaded:', lfw.images.shape[0], 'images,', len(lfw.target_names), 'identities')\n",
        "\n",
        "output_dir = 'lfw_persons'\n",
        "os.makedirs(output_dir, exist_ok=True)\n",
        "\n",
        "for i, name in enumerate(lfw.target_names):\n",
        "    mask = lfw.target == i\n",
        "    if mask.sum() < 10:\n",
        "        continue\n",
        "    person_dir = os.path.join(output_dir, name.replace(' ', '_'))\n",
        "    os.makedirs(person_dir, exist_ok=True)\n",
        "    for j, idx in enumerate(np.where(mask)[0]):\n",
        "        img = Image.fromarray(lfw.images[idx].astype(np.uint8))\n",
        "        img = img.resize((112, 112), Image.BILINEAR)\n",
        "        img.save(os.path.join(person_dir, str(j).zfill(4) + '.jpg'))\n",
        "\n",
        "persons = [d for d in os.listdir(output_dir) if os.path.isdir(os.path.join(output_dir, d))]\n",
        "print('Saved', len(persons), 'persons to', output_dir)"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 3: MobileFaceNet Architecture\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "\n",
        "class DWSep(nn.Module):\n",
        "    def __init__(self, ic, oc, st=1):\n",
        "        super().__init__()\n",
        "        self.dw = nn.Conv2d(ic, ic, 3, st, 1, groups=ic, bias=False)\n",
        "        self.b1 = nn.BatchNorm2d(ic)\n",
        "        self.pw = nn.Conv2d(ic, oc, 1, bias=False)\n",
        "        self.b2 = nn.BatchNorm2d(oc)\n",
        "    def forward(self, x):\n",
        "        return F.relu(self.b2(self.pw(F.relu(self.b1(self.dw(x))))))\n",
        "\n",
        "class SE(nn.Module):\n",
        "    def __init__(self, ch, r=4):\n",
        "        super().__init__()\n",
        "        m = max(ch // r, 8)\n",
        "        self.se = nn.Sequential(\n",
        "            nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n",
        "            nn.Linear(ch, m), nn.ReLU(True),\n",
        "            nn.Linear(m, ch), nn.Sigmoid())\n",
        "    def forward(self, x):\n",
        "        return x * self.se(x).unsqueeze(-1).unsqueeze(-1)\n",
        "\n",
        "class MB(nn.Module):\n",
        "    def __init__(self, ic, oc, st=1):\n",
        "        super().__init__()\n",
        "        m = ic * 2\n",
        "        self.ex = nn.Sequential(\n",
        "            nn.Conv2d(ic, m, 1, bias=False), nn.BatchNorm2d(m), nn.ReLU(True))\n",
        "        self.dw = DWSep(m, oc, st)\n",
        "        self.se = SE(oc)\n",
        "        self.res = (st == 1 and ic == oc)\n",
        "    def forward(self, x):\n",
        "        o = self.se(self.dw(self.ex(x)))\n",
        "        return o + x if self.res else o\n",
        "\n",
        "class MobileFaceNet(nn.Module):\n",
        "    def __init__(self, ed=128):\n",
        "        super().__init__()\n",
        "        self.stem = nn.Sequential(\n",
        "            nn.Conv2d(3, 64, 3, 2, 1, bias=False),\n",
        "            nn.BatchNorm2d(64), nn.ReLU(True))\n",
        "        self.blk = nn.Sequential(\n",
        "            MB(64, 64), MB(64, 128, 2), MB(128, 128),\n",
        "            MB(128, 256, 2), MB(256, 256), MB(256, 256),\n",
        "            MB(256, 512, 2), MB(512, 512), MB(512, 512))\n",
        "        self.fin = nn.Sequential(\n",
        "            nn.Conv2d(512, 512, 3, groups=512, bias=False),\n",
        "            nn.BatchNorm2d(512), nn.ReLU(True),\n",
        "            nn.Conv2d(512, ed, 1, bias=False), nn.BatchNorm2d(ed))\n",
        "    def forward(self, x):\n",
        "        x = self.fin(self.blk(self.stem(x)))\n",
        "        return F.normalize(x.view(x.size(0), -1), p=2, dim=1)\n",
        "\n",
        "model = MobileFaceNet(128)\n",
        "nparams = sum(p.numel() for p in model.parameters())\n",
        "print('MobileFaceNet params:', nparams)\n",
        "print('Output shape:', model(torch.randn(2, 3, 112, 112)).shape)"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 4: DataLoader\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "import random, glob\n",
        "\n",
        "class LFWDataset(Dataset):\n",
        "    def __init__(self, root='lfw_persons', max_identities=100, augment=True):\n",
        "        self.samples = []\n",
        "        self.augment = augment\n",
        "        dirs = sorted([d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))])\n",
        "        dirs = dirs[:max_identities]\n",
        "        for i, identity in enumerate(dirs):\n",
        "            for p in glob.glob(os.path.join(root, identity, '*.jpg')):\n",
        "                self.samples.append((p, i))\n",
        "        print(len(self.samples), 'images,', len(dirs), 'identities')\n",
        "    def __len__(self):\n",
        "        return len(self.samples)\n",
        "    def __getitem__(self, idx):\n",
        "        path, label = self.samples[idx]\n",
        "        img = Image.open(path).convert('RGB').resize((112, 112))\n",
        "        arr = np.array(img).astype(np.float32) / 255.0\n",
        "        if self.augment:\n",
        "            if random.random() > 0.5:\n",
        "                arr = np.clip(arr + np.random.uniform(-0.12, 0.12), 0, 1)\n",
        "            if random.random() > 0.5:\n",
        "                arr = np.flip(arr, axis=1).copy()\n",
        "        tensor = torch.from_numpy(arr).permute(2, 0, 1).float()\n",
        "        mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)\n",
        "        std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)\n",
        "        return (tensor - mean) / std, label\n",
        "\n",
        "train_ds = LFWDataset('lfw_persons', 80, augment=True)\n",
        "val_ds = LFWDataset('lfw_persons', 100, augment=False)\n",
        "train_loader = DataLoader(train_ds, batch_size=64, shuffle=True, num_workers=2, pin_memory=True)\n",
        "val_loader = DataLoader(val_ds, batch_size=64, shuffle=False, num_workers=2)\n",
        "print('Train:', len(train_ds), 'Val:', len(val_ds))"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 5: Train 10 Epochs\n",
        "import time\n",
        "from tqdm import tqdm\n",
        "\n",
        "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "model = MobileFaceNet(128).to(DEVICE)\n",
        "criterion = nn.CrossEntropyLoss()\n",
        "optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)\n",
        "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10, eta_min=1e-6)\n",
        "best_acc = 0\n",
        "\n",
        "for epoch in range(10):\n",
        "    t0 = time.time()\n",
        "    model.train()\n",
        "    train_correct = 0\n",
        "    train_total = 0\n",
        "    for images, labels in tqdm(train_loader, desc='Epoch ' + str(epoch + 1) + '/10'):\n",
        "        images, labels = images.to(DEVICE), labels.to(DEVICE)\n",
        "        optimizer.zero_grad()\n",
        "        outputs = model(images)\n",
        "        loss = criterion(outputs, labels)\n",
        "        loss.backward()\n",
        "        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)\n",
        "        optimizer.step()\n",
        "        train_correct += (outputs.argmax(1) == labels).sum().item()\n",
        "        train_total += labels.size(0)\n",
        "    model.eval()\n",
        "    val_correct = 0\n",
        "    val_total = 0\n",
        "    with torch.no_grad():\n",
        "        for images, labels in val_loader:\n",
        "            images, labels = images.to(DEVICE), labels.to(DEVICE)\n",
        "            val_correct += (model(images).argmax(1) == labels).sum().item()\n",
        "            val_total += labels.size(0)\n",
        "    train_acc = 100.0 * train_correct / train_total\n",
        "    val_acc = 100.0 * val_correct / val_total\n",
        "    scheduler.step()\n",
        "    elapsed = int(time.time() - t0)\n",
        "    print('Epoch ' + str(epoch + 1) + ': Train ' + str(round(train_acc, 1)) + '% Val ' + str(round(val_acc, 1)) + '% ' + str(elapsed) + 's')\n",
        "    if val_acc > best_acc:\n",
        "        best_acc = val_acc\n",
        "        torch.save(model.state_dict(), 'rec_best.pt')\n",
        "        print('  Saved best model (' + str(round(val_acc, 1)) + '%)')\n",
        "print('Training complete. Best: ' + str(round(best_acc, 1)) + '%')"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 6: Export ONNX\n",
        "model.cpu().eval()\n",
        "torch.onnx.export(\n",
        "    model, torch.randn(1, 3, 112, 112),\n",
        "    'face_recognition.onnx',\n",
        "    input_names=['input'],\n",
        "    output_names=['output'],\n",
        "    opset_version=13,\n",
        "    dynamo=False)\n",
        "sz = os.path.getsize('face_recognition.onnx') / 1e6\n",
        "print('Exported: face_recognition.onnx (' + str(round(sz, 1)) + 'MB)')\n",
        "print('Download and place in F:/PROJECTS/NetraEdge/models/')"
    ], "outputs": [], "execution_count": None}
]

rec_nb = {
    "nbformat": 4, "nbformat_minor": 0,
    "metadata": {"accelerator": "GPU", "colab": {"gpuType": "T4"}, "kernelspec": {"display_name": "Python 3", "name": "python3"}},
    "cells": rec_cells
}
with open(r'F:\PROJECTS\NetraEdge\training\notebooks\train_recognition.ipynb', 'w', encoding='utf-8') as f:
    json.dump(rec_nb, f, indent=1)
print('train_recognition.ipynb OK')

# ============ LIVENESS NOTEBOOK ============
liv_cells = [
    {"cell_type": "markdown", "metadata": {}, "source": [
        "# NetraEdge - Liveness Detection Training\n",
        "## LivenessCNN: Real vs Print vs Screen | GPU: T4 | ~1 hour"
    ]},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 1: Install + GPU Check\n",
        "!pip install -q onnx tqdm scikit-learn onnxscript\n",
        "import torch\n",
        "print('PyTorch:', torch.__version__)\n",
        "if torch.cuda.is_available():\n",
        "    print('GPU:', torch.cuda.get_device_name())\n",
        "else:\n",
        "    print('WARNING: No GPU! Runtime > Change runtime type > GPU')"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 2: Load LFW + Generate Spoof Data\n",
        "from sklearn.datasets import fetch_lfw_people\n",
        "from PIL import Image\n",
        "import numpy as np\n",
        "import os, random\n",
        "\n",
        "print('Loading LFW via sklearn...')\n",
        "lfw = fetch_lfw_people(min_faces_per_person=20, resize=0.5, color=True)\n",
        "print('Loaded:', lfw.images.shape[0], 'images,', len(lfw.target_names), 'identities')\n",
        "\n",
        "output_dir = 'lfw_persons'\n",
        "os.makedirs(output_dir, exist_ok=True)\n",
        "for i, name in enumerate(lfw.target_names):\n",
        "    mask = lfw.target == i\n",
        "    if mask.sum() < 10:\n",
        "        continue\n",
        "    person_dir = os.path.join(output_dir, name.replace(' ', '_'))\n",
        "    os.makedirs(person_dir, exist_ok=True)\n",
        "    for j, idx in enumerate(np.where(mask)[0]):\n",
        "        img = Image.fromarray(lfw.images[idx].astype(np.uint8))\n",
        "        img = img.resize((112, 112), Image.BILINEAR)\n",
        "        img.save(os.path.join(person_dir, str(j).zfill(4) + '.jpg'))\n",
        "\n",
        "persons = [d for d in os.listdir(output_dir) if os.path.isdir(os.path.join(output_dir, d))]\n",
        "print('Saved', len(persons), 'persons to', output_dir)"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 3: LivenessCNN Architecture\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "\n",
        "class LBlock(nn.Module):\n",
        "    def __init__(self, ic, oc, st=1):\n",
        "        super().__init__()\n",
        "        self.dw = nn.Conv2d(ic, ic, 3, st, 1, groups=ic, bias=False)\n",
        "        self.b1 = nn.BatchNorm2d(ic)\n",
        "        self.pw = nn.Conv2d(ic, oc, 1, bias=False)\n",
        "        self.b2 = nn.BatchNorm2d(oc)\n",
        "    def forward(self, x):\n",
        "        return F.relu(self.b2(self.pw(F.relu(self.b1(self.dw(x))))))\n",
        "\n",
        "class LivenessCNN(nn.Module):\n",
        "    def __init__(self, nc=3, dp=0.3):\n",
        "        super().__init__()\n",
        "        self.feat = nn.Sequential(\n",
        "            nn.Conv2d(3, 32, 3, 2, 1, bias=False), nn.BatchNorm2d(32), nn.ReLU(True),\n",
        "            LBlock(32, 64), LBlock(64, 128, 2),\n",
        "            LBlock(128, 256, 2), LBlock(256, 256, 2))\n",
        "        self.cls = nn.Sequential(\n",
        "            nn.AdaptiveAvgPool2d(1), nn.Flatten(),\n",
        "            nn.Dropout(dp), nn.Linear(256, 64), nn.ReLU(True),\n",
        "            nn.Dropout(dp * 0.5), nn.Linear(64, nc))\n",
        "        for m in self.modules():\n",
        "            if isinstance(m, nn.Conv2d):\n",
        "                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')\n",
        "            elif isinstance(m, nn.BatchNorm2d):\n",
        "                nn.init.constant_(m.weight, 1)\n",
        "                nn.init.constant_(m.bias, 0)\n",
        "    def forward(self, x):\n",
        "        return self.cls(self.feat(x))\n",
        "\n",
        "livmodel = LivenessCNN(3)\n",
        "out = livmodel(torch.randn(2, 3, 112, 112))\n",
        "nparams = sum(p.numel() for p in livmodel.parameters())\n",
        "print('LivenessCNN:', nparams, 'params, output:', out.shape)"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 4: Synthetic Liveness Dataset\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "\n",
        "class SynLiveness(Dataset):\n",
        "    def __init__(self, root='lfw_persons', ns=3000):\n",
        "        self.imgs = []\n",
        "        for r, ds, fs in os.walk(root):\n",
        "            for f in fs:\n",
        "                if f.endswith('.jpg'):\n",
        "                    self.imgs.append(os.path.join(r, f))\n",
        "        self.ns = ns\n",
        "        print('Found', len(self.imgs), 'source images')\n",
        "    def __len__(self):\n",
        "        return self.ns\n",
        "    def __getitem__(self, idx):\n",
        "        path = random.choice(self.imgs)\n",
        "        label = idx % 3\n",
        "        img = Image.open(path).convert('RGB').resize((112, 112))\n",
        "        arr = np.array(img).astype(np.float32) / 255.0\n",
        "        if label == 1:\n",
        "            arr = np.clip(arr * 1.1 + 0.04, 0, 1)\n",
        "            k = np.ones(9) / 9\n",
        "            arr = np.stack([np.convolve(arr[:,:,c].flatten(), k, mode='same').reshape(112,112) for c in range(3)], -1)\n",
        "        elif label == 2:\n",
        "            for y in range(0, 112, 2):\n",
        "                arr[y,:,:] *= 0.85\n",
        "            arr[:,:,2] *= 1.1\n",
        "            arr = arr * 0.8 + 0.12\n",
        "        arr = np.clip(arr + np.random.normal(0, 0.02, arr.shape), 0, 1)\n",
        "        if random.random() > 0.5:\n",
        "            arr = np.flip(arr, axis=1).copy()\n",
        "        tensor = torch.from_numpy(arr).permute(2, 0, 1).float()\n",
        "        mean = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)\n",
        "        std = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)\n",
        "        return (tensor - mean) / std, label\n",
        "\n",
        "train_ds = SynLiveness('lfw_persons', 3000)\n",
        "val_ds = SynLiveness('lfw_persons', 600)\n",
        "train_loader = DataLoader(train_ds, batch_size=64, shuffle=True, num_workers=2, pin_memory=True)\n",
        "val_loader = DataLoader(val_ds, batch_size=64, shuffle=False, num_workers=2)\n",
        "print('Train:', len(train_ds), 'Val:', len(val_ds))"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 5: Train 15 Epochs\n",
        "import time\n",
        "from tqdm import tqdm\n",
        "\n",
        "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "livmodel = LivenessCNN(3).to(DEVICE)\n",
        "weights = torch.tensor([1.0, 1.5, 1.5]).to(DEVICE)\n",
        "criterion = nn.CrossEntropyLoss(weight=weights, label_smoothing=0.1)\n",
        "optimizer = torch.optim.AdamW(livmodel.parameters(), lr=5e-4, weight_decay=1e-4)\n",
        "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=15, eta_min=1e-6)\n",
        "best_acc = 0\n",
        "\n",
        "for epoch in range(15):\n",
        "    t0 = time.time()\n",
        "    livmodel.train()\n",
        "    train_correct = 0\n",
        "    train_total = 0\n",
        "    for images, labels in tqdm(train_loader, desc='Epoch ' + str(epoch + 1) + '/15'):\n",
        "        images, labels = images.to(DEVICE), labels.to(DEVICE)\n",
        "        optimizer.zero_grad()\n",
        "        loss = criterion(livmodel(images), labels)\n",
        "        loss.backward()\n",
        "        torch.nn.utils.clip_grad_norm_(livmodel.parameters(), 5.0)\n",
        "        optimizer.step()\n",
        "        train_correct += (livmodel(images).argmax(1) == labels).sum().item()\n",
        "        train_total += labels.size(0)\n",
        "    livmodel.eval()\n",
        "    val_correct = 0\n",
        "    val_total = 0\n",
        "    with torch.no_grad():\n",
        "        for images, labels in val_loader:\n",
        "            images, labels = images.to(DEVICE), labels.to(DEVICE)\n",
        "            val_correct += (livmodel(images).argmax(1) == labels).sum().item()\n",
        "            val_total += labels.size(0)\n",
        "    train_acc = 100.0 * train_correct / train_total\n",
        "    val_acc = 100.0 * val_correct / val_total\n",
        "    scheduler.step()\n",
        "    elapsed = int(time.time() - t0)\n",
        "    print('Epoch ' + str(epoch + 1) + ': Train ' + str(round(train_acc, 1)) + '% Val ' + str(round(val_acc, 1)) + '% ' + str(elapsed) + 's')\n",
        "    if val_acc > best_acc:\n",
        "        best_acc = val_acc\n",
        "        torch.save(livmodel.state_dict(), 'liv_best.pt')\n",
        "        print('  Saved best model (' + str(round(val_acc, 1)) + '%)')\n",
        "print('Training complete. Best: ' + str(round(best_acc, 1)) + '%')"
    ], "outputs": [], "execution_count": None},
    {"cell_type": "code", "metadata": {}, "source": [
        "#@title Step 6: Export ONNX\n",
        "livmodel.cpu().eval()\n",
        "torch.onnx.export(\n",
        "    livmodel, torch.randn(1, 3, 112, 112),\n",
        "    'liveness_detector.onnx',\n",
        "    input_names=['input'],\n",
        "    output_names=['output'],\n",
        "    opset_version=13,\n",
        "    dynamo=False)\n",
        "sz = os.path.getsize('liveness_detector.onnx') / 1e6\n",
        "print('Exported: liveness_detector.onnx (' + str(round(sz, 1)) + 'MB)')\n",
        "print('Download and place in F:/PROJECTS/NetraEdge/models/')"
    ], "outputs": [], "execution_count": None}
]

liv_nb = {
    "nbformat": 4, "nbformat_minor": 0,
    "metadata": {"accelerator": "GPU", "colab": {"gpuType": "T4"}, "kernelspec": {"display_name": "Python 3", "name": "python3"}},
    "cells": liv_cells
}
with open(r'F:\PROJECTS\NetraEdge\training\notebooks\train_liveness.ipynb', 'w', encoding='utf-8') as f:
    json.dump(liv_nb, f, indent=1)
print('train_liveness.ipynb OK')

# Verify both
for nb_name in ['train_recognition.ipynb', 'train_liveness.ipynb']:
    path = r'F:\PROJECTS\NetraEdge\training\notebooks' + '\\' + nb_name
    with open(path) as f:
        json.load(f)
    print(nb_name + ': valid JSON')
